CREATE TABLE FDV_ONLINE.REPRESENTACAO (
	ID SERIAL,
	IDREPRESENTANTE SERIAL REFERENCES FDV_ONLINE.REPRESENTANTE(ID) NOT NULL,
	IDMARCA SERIAL REFERENCES FDV_ONLINE.MARCA(ID) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.REPRESENTACAO (IDREPRESENTANTE, IDMARCA) VALUES (1,1);
INSERT INTO FDV_ONLINE.REPRESENTACAO (IDREPRESENTANTE, IDMARCA) VALUES (2,1);
INSERT INTO FDV_ONLINE.REPRESENTACAO (IDREPRESENTANTE, IDMARCA) VALUES (3,14);
INSERT INTO FDV_ONLINE.REPRESENTACAO (IDREPRESENTANTE, IDMARCA) VALUES (4,1);
INSERT INTO FDV_ONLINE.REPRESENTACAO (IDREPRESENTANTE, IDMARCA) VALUES (5,1);
INSERT INTO FDV_ONLINE.REPRESENTACAO (IDREPRESENTANTE, IDMARCA) VALUES (6,7);
INSERT INTO FDV_ONLINE.REPRESENTACAO (IDREPRESENTANTE, IDMARCA) VALUES (7,14);
INSERT INTO FDV_ONLINE.REPRESENTACAO (IDREPRESENTANTE, IDMARCA) VALUES (8,1);
INSERT INTO FDV_ONLINE.REPRESENTACAO (IDREPRESENTANTE, IDMARCA) VALUES (8,7);
INSERT INTO FDV_ONLINE.REPRESENTACAO (IDREPRESENTANTE, IDMARCA) VALUES (8,14);