CREATE TABLE FDV_ONLINE.SUPERVISAO (
	ID SERIAL,
	IDREPRESENTANTE SERIAL REFERENCES FDV_ONLINE.REPRESENTANTE(ID) NOT NULL,
	IDSUPERVISOR SERIAL REFERENCES FDV_ONLINE.REPRESENTANTE(ID) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.SUPERVISAO (IDREPRESENTANTE, IDSUPERVISOR) VALUES (8,1);
INSERT INTO FDV_ONLINE.SUPERVISAO (IDREPRESENTANTE, IDSUPERVISOR) VALUES (8,2);
INSERT INTO FDV_ONLINE.SUPERVISAO (IDREPRESENTANTE, IDSUPERVISOR) VALUES (8,3);
INSERT INTO FDV_ONLINE.SUPERVISAO (IDREPRESENTANTE, IDSUPERVISOR) VALUES (8,4);
INSERT INTO FDV_ONLINE.SUPERVISAO (IDREPRESENTANTE, IDSUPERVISOR) VALUES (8,5);
INSERT INTO FDV_ONLINE.SUPERVISAO (IDREPRESENTANTE, IDSUPERVISOR) VALUES (8,6);
INSERT INTO FDV_ONLINE.SUPERVISAO (IDREPRESENTANTE, IDSUPERVISOR) VALUES (8,7);