CREATE TABLE FDV_ONLINE.ROLE (
	ID SERIAL,
	NOME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.ROLE (NOME) VALUES ('ADMIN');
INSERT INTO FDV_ONLINE.ROLE (NOME) VALUES ('REPRESENTANTE');
INSERT INTO FDV_ONLINE.ROLE (NOME) VALUES ('SUPERVISOR');
