CREATE TABLE FDV_ONLINE.REPRESENTANTEROLES (
	ID SERIAL,
	IDREPRESENTANTE SERIAL REFERENCES FDV_ONLINE.REPRESENTANTE(ID) NOT NULL,
	IDROLE SERIAL REFERENCES FDV_ONLINE.ROLE(ID) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.REPRESENTANTEROLES (IDROLE, IDREPRESENTANTE) VALUES (2,1);
INSERT INTO FDV_ONLINE.REPRESENTANTEROLES (IDROLE, IDREPRESENTANTE) VALUES (2,2);
INSERT INTO FDV_ONLINE.REPRESENTANTEROLES (IDROLE, IDREPRESENTANTE) VALUES (2,3);
INSERT INTO FDV_ONLINE.REPRESENTANTEROLES (IDROLE, IDREPRESENTANTE) VALUES (2,4);
INSERT INTO FDV_ONLINE.REPRESENTANTEROLES (IDROLE, IDREPRESENTANTE) VALUES (2,5);
INSERT INTO FDV_ONLINE.REPRESENTANTEROLES (IDROLE, IDREPRESENTANTE) VALUES (2,6);
INSERT INTO FDV_ONLINE.REPRESENTANTEROLES (IDROLE, IDREPRESENTANTE) VALUES (2,7);
INSERT INTO FDV_ONLINE.REPRESENTANTEROLES (IDROLE, IDREPRESENTANTE) VALUES (2,8);
INSERT INTO FDV_ONLINE.REPRESENTANTEROLES (IDROLE, IDREPRESENTANTE) VALUES (2,8);
INSERT INTO FDV_ONLINE.REPRESENTANTEROLES (IDROLE, IDREPRESENTANTE) VALUES (3,8);