CREATE TABLE FDV_ONLINE.CATEGORIA (
	ID SERIAL,
	NOME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.CATEGORIA (NOME) VALUES ('SAPATO');
INSERT INTO FDV_ONLINE.CATEGORIA (NOME) VALUES ('BOTA');
INSERT INTO FDV_ONLINE.CATEGORIA (NOME) VALUES ('TÊNIS');
INSERT INTO FDV_ONLINE.CATEGORIA (NOME) VALUES ('SANDÁLIA');
INSERT INTO FDV_ONLINE.CATEGORIA (NOME) VALUES ('BOLSA');
INSERT INTO FDV_ONLINE.CATEGORIA (NOME) VALUES ('SAPATILHA');
