CREATE TABLE FDV_ONLINE.DEPARTAMENTO (
	ID SERIAL,
	NOME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.DEPARTAMENTO (NOME) VALUES ('FEMININO');
INSERT INTO FDV_ONLINE.DEPARTAMENTO (NOME) VALUES ('MASCULINO');
INSERT INTO FDV_ONLINE.DEPARTAMENTO (NOME) VALUES ('INFANTIL');