CREATE TABLE IF NOT EXISTS FDV_ONLINE.COLECAO (
	ID SERIAL,
	NOME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.COLECAO (NOME) VALUES ('PRIMAVERA/VERÃO 2016');
INSERT INTO FDV_ONLINE.COLECAO (NOME) VALUES ('OUTONO/INVERNO 2016');
INSERT INTO FDV_ONLINE.COLECAO (NOME) VALUES ('PRIMAVERA/VERÃO 2015');