CREATE TABLE FDV_ONLINE.PRODUTO (
	ID SERIAL,
	IDMODELO SERIAL REFERENCES FDV_ONLINE.MODELO(ID) NOT NULL,
	COR VARCHAR(50) NOT NULL,
	PRECO DECIMAL(5,2) NOT NULL,
	PRECO_PROMOCAO DECIMAL(5,2),
	IMAGEM_PRINCIPAL VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.PRODUTO (IDMODELO, COR, PRECO, PRECO_PROMOCAO, IMAGEM_PRINCIPAL) VALUES (2, 'PRETO/PRATA', 109.99, 89.99, '../images/produtos/produto1/principal.jpg');
INSERT INTO FDV_ONLINE.PRODUTO (IDMODELO, COR, PRECO, PRECO_PROMOCAO, IMAGEM_PRINCIPAL) VALUES (3, 'ROSA', 99.99, 89.99, '../images/produtos/produto2/principal.jpg');
