CREATE TABLE IF NOT EXISTS FDV_ONLINE.IMAGEM_PRODUTO (
	ID SERIAL,
	IDPRODUTO SERIAL REFERENCES FDV_ONLINE.PRODUTO(ID) NOT NULL,
	IMAGEM VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.IMAGEM_PRODUTO (IDPRODUTO, IMAGEM) VALUES (1, '../images/produtos/produto1/1.jpg');
INSERT INTO FDV_ONLINE.IMAGEM_PRODUTO (IDPRODUTO, IMAGEM) VALUES (1, '../images/produtos/produto1/2.jpg');
INSERT INTO FDV_ONLINE.IMAGEM_PRODUTO (IDPRODUTO, IMAGEM) VALUES (1, '../images/produtos/produto1/3.jpg');
INSERT INTO FDV_ONLINE.IMAGEM_PRODUTO (IDPRODUTO, IMAGEM) VALUES (1, '../images/produtos/produto1/4.jpg');
INSERT INTO FDV_ONLINE.IMAGEM_PRODUTO (IDPRODUTO, IMAGEM) VALUES (1, '../images/produtos/produto2/1.jpg');
INSERT INTO FDV_ONLINE.IMAGEM_PRODUTO (IDPRODUTO, IMAGEM) VALUES (1, '../images/produtos/produto2/2.jpg');
INSERT INTO FDV_ONLINE.IMAGEM_PRODUTO (IDPRODUTO, IMAGEM) VALUES (1, '../images/produtos/produto2/3.jpg');
INSERT INTO FDV_ONLINE.IMAGEM_PRODUTO (IDPRODUTO, IMAGEM) VALUES (1, '../images/produtos/produto2/4.jpg');
