CREATE TABLE IF NOT EXISTS FDV_ONLINE.PEDIDO (
	ID SERIAL,
	IDCLIENTE SERIAL REFERENCES FDV_ONLINE.CLIENTE(ID) NOT NULL,
	IDREPRESENTANTE SERIAL REFERENCES FDV_ONLINE.REPRESENTANTE(ID) NOT NULL,
	DATA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.PEDIDO (IDCLIENTE, IDREPRESENTANTE) VALUES (1, 1);
INSERT INTO FDV_ONLINE.PEDIDO (IDCLIENTE, IDREPRESENTANTE) VALUES (2, 1);
