INSERT INTO FDV_ONLINE.MODELO (NOME, IDMARCA, IDCATEGORIA, IDDEPARTAMENTO, IDCOLECAO) VALUES ('Sandália Via Marte ZZX', 12, 4, 1, 1);
INSERT INTO FDV_ONLINE.MODELO (NOME, IDMARCA, IDCATEGORIA, IDDEPARTAMENTO, IDCOLECAO) VALUES ('Sandália Via Marte HYR', 12, 4, 1, 1);

INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('ConfortFlex');
INSERT INTO FDV_ONLINE.MODELO (NOME, IDMARCA, IDCATEGORIA, IDDEPARTAMENTO, IDCOLECAO) VALUES ('Sandália ConfortFlex', 15, 4, 1, 1);

INSERT INTO FDV_ONLINE.MODELO (NOME, IDMARCA, IDCATEGORIA, IDDEPARTAMENTO, IDCOLECAO) VALUES ('Sandália Via Marte UUE', 12, 4, 1, 1);
INSERT INTO FDV_ONLINE.MODELO (NOME, IDMARCA, IDCATEGORIA, IDDEPARTAMENTO, IDCOLECAO) VALUES ('Sandália Bottero', 1, 4, 1, 1);
INSERT INTO FDV_ONLINE.MODELO (NOME, IDMARCA, IDCATEGORIA, IDDEPARTAMENTO, IDCOLECAO) VALUES ('Sandália Tanara TRW', 5, 4, 1, 1);
INSERT INTO FDV_ONLINE.MODELO (NOME, IDMARCA, IDCATEGORIA, IDDEPARTAMENTO, IDCOLECAO) VALUES ('Sandália Via Marte HYR', 12, 4, 1, 1);