CREATE TABLE FDV_ONLINE.PAIS (
	ID SERIAL,
	NOME VARCHAR(255) NOT NULL,
	SIGLA VARCHAR(3) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Brasil', 'BRA');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Alemanha', 'DEU');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Paraguai', 'PRY');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Panamá', 'PAN');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('México','MEX');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('China','CHN');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Estados Unidos','EUA');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Argentina','ARG');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Uruguai', 'URY');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Cingapura', 'SGP');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Perú', 'PER');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Porto Rico', 'PRI');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Uruguai', 'URY');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('Itália', 'ITA');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('França', 'FRA');
INSERT INTO FDV_ONLINE.PAIS (NOME, SIGLA) VALUES ('El Salvador', 'SLV');