CREATE TABLE FDV_ONLINE.ESTADO (
	ID SERIAL,
	NOME VARCHAR(255) NOT NULL,
	SIGLA VARCHAR(3),
	IDPAIS SERIAL REFERENCES FDV_ONLINE.PAIS(ID) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Rio Grande do Sul', 'RS', 1);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Santa Catarina', 'SC', 1);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Paraná', 'PR', 1);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('São Paulo', 'SP', 1);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Rio de Janeiro', 'RJ', 1);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Mato Grosso do Sul', 'MS', 1);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Baden-Württemberg', 'BW', 2);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Baixa Saxônia', 'NI', 2);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Baviera', 'BY', 2);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Berlim', 'BE', 2);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Brandemburgo', 'BB', 2);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Chihuahua', 'CH', 5);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Distrito Federal', 'DF', 5);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Estado de México', 'ME', 5);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Yucatán', 'YN', 5);
INSERT INTO FDV_ONLINE.ESTADO (NOME, SIGLA, IDPAIS) VALUES ('Veracruz', 'VZ', 5);