CREATE TABLE FDV_ONLINE.ENDERECO (
	ID SERIAL,
	LOGRADOURO VARCHAR(255) NOT NULL,
	CEP VARCHAR(25) NOT NULL,
	IDCIDADE SERIAL REFERENCES FDV_ONLINE.CIDADE(ID) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua da Fazenda, nº 300, Bairro Centro', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Av. Bento Gonçalves, nº 3432, Bairro Floresta', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua das Flores, nº 444, Bairro Centro', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua da Fazenda, nº 300, Bairro Centro', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua da Fazenda, nº 432, Bairro Centro', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua Conceição, nº 1111, Bairro Centro', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua Marte, nº 432, Bairro Partenon', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua 7 de setembro, nº 7655, Bairro Três Figueiras', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua 20 de setembro, nº 7655, Bairro Centro', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua 20 de setembro, nº 7658, Bairro Centro', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua 7 de setembro, nº 7657, Bairro Centro', 90610032, 2);
INSERT INTO FDV_ONLINE.ENDERECO (LOGRADOURO, CEP, IDCIDADE) VALUES ('Rua 21 de setembro, nº 7659, Bairro Centro', 90610032, 2);

