CREATE TABLE FDV_ONLINE.ENDERECOENTREGA (
	ID SERIAL,
	IDENDERECO SERIAL REFERENCES FDV_ONLINE.ENDERECO(ID) NOT NULL,
	IDCLIENTE SERIAL REFERENCES FDV_ONLINE.CLIENTE(ID) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (1,1);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (2,2);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (3,3);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (4,4);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (5,5);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (6,6);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (7,7);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (8,8);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (9,9);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (10,9);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (11,9);
INSERT INTO FDV_ONLINE.ENDERECOENTREGA (IDENDERECO, IDCLIENTE) VALUES (12,9);