CREATE TABLE FDV_ONLINE.MARCA (
	ID SERIAL,
	NOME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Bottero');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Cravo & Canela');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Dakota');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Vizzano');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Tanara');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Calvin Klein');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Democrata');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Ferracini');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Adidas');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Lacoste');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Pegada');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Via Marte');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Lillys Closet');
INSERT INTO FDV_ONLINE.MARCA (NOME) VALUES ('Dumond');